version: '3.1'

services:
  new-web:
    build: ../new-server
    restart: always
    environment:
      - POSTGRES_HOST=pg
      - PORT=8080
    ports:
      - "8080:8080"
    links:
      - pg
  pg:
    image: postgres:10-alpine
    restart: always
    ports:
      - "5432:5432"
  old-web:
    build: ../old-server
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo
      - MONGO_DB_NAME=quotes
      - MONGO_DB_COLLECTION=quotes
      - PORT=8081
    ports:
      - "8081:8081"
    links:
      - mongo
  mongo:
    restart: always
    image: mongo:latest
    ports:
      - "27017:27017"