version: '3.1'

services:
  web:
    build: ./
    restart: always
    environment:
      - SEED=true
      - POSTGRES_HOST=database
      - PORT=8081
    ports:
      - "8081:8081"
    links:
      - database
  database:
    image: postgres:10-alpine
    restart: always
    ports:
        - "5432:5432"
