version: '3.1'

services:
  web:
    build: ./
    restart: always
    environment:
      - MONGO_URI=mongodb://database
      - MONGO_DB_NAME=quotes
      - MONGO_DB_COLLECTION=quotes
      - PORT=8081
      - SEEDS=true
    ports:
      - "8081:8081"
    links:
      - database
  database:
    restart: always
    image: mongo:latest
    ports:
      - "27017:27017"
