const quotes = require("./data_seeds.json")
const {writeFileSync} = require('fs')
const { join } = require('path')

const insertQuotes = () => `INSERT INTO quotes.quote ( author, quote ) VALUES
${quotes.map(item => `('${item.author}', '${item.quote}')`).join(',\n')};
`;

const content = `-- WARNING: This file was auto-generated by a script (seed/index.js). Please modify the script and not this file.
-- Populate tables with mocked values for testing.

${insertQuotes()}

`;

writeFileSync(join(__dirname, '../sql/queries/insert-mocked-data.sql'), content);
