-- WARNING: This file was auto-generated by a script (seed/index.js). Please modify the script and not this file.
-- Populate tables with mocked values for testing.

INSERT INTO quotes.quote ( author, quote ) VALUES
('Lauren Mosenthal', 'Life is a series of building, testing, changing and iterating.'),
('Linus Torvalds', 'Talk is cheap. Show me the code.');


